"""Data source management — load, fetch, convert, merge, deduplicate."""

from __future__ import annotations

import json
import os
import ssl
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

import aiohttp


def _fetch_ssl_ctx() -> ssl.SSLContext:
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE
    return ctx

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

_PKG_DIR = Path(__file__).resolve().parent
_REPO_ROOT = _PKG_DIR.parent
_WMN_DATA = _REPO_ROOT / "wmn-data.json"
_EXTENDED_DATA = _PKG_DIR / "data" / "extended_sites.json"
_CACHE_DIR = Path.home() / ".cache" / "whatsmyname"

# Remote data source URLs (raw GitHub)
SHERLOCK_DATA_URL = (
    "https://raw.githubusercontent.com/sherlock-project/sherlock/"
    "master/sherlock_project/resources/data.json"
)
MAIGRET_DATA_URL = (
    "https://raw.githubusercontent.com/soxoj/maigret/"
    "main/maigret/resources/data.json"
)


def _ensure_cache_dir() -> Path:
    _CACHE_DIR.mkdir(parents=True, exist_ok=True)
    return _CACHE_DIR


# ---------------------------------------------------------------------------
# Local loaders
# ---------------------------------------------------------------------------


def load_wmn_data() -> list[dict[str, Any]]:
    """Load the built-in wmn-data.json sites."""
    if not _WMN_DATA.exists():
        return []
    with open(_WMN_DATA, encoding="utf-8") as f:
        data = json.load(f)
    sites = data.get("sites", [])
    # Tag the source
    for s in sites:
        s.setdefault("_source", "wmn")
    return sites


def load_extended_data() -> list[dict[str, Any]]:
    """Load the extended_sites.json generated by generate_sites.py."""
    if not _EXTENDED_DATA.exists():
        return []
    with open(_EXTENDED_DATA, encoding="utf-8") as f:
        data = json.load(f)
    sites = data.get("sites", []) if isinstance(data, dict) else data
    for s in sites:
        s.setdefault("_source", "extended")
    return sites


def load_cached_remote(name: str) -> list[dict[str, Any]]:
    """Load cached remote data (Sherlock or Maigret)."""
    cache_file = _CACHE_DIR / f"{name}.json"
    if not cache_file.exists():
        return []
    with open(cache_file, encoding="utf-8") as f:
        data = json.load(f)
    return data


# ---------------------------------------------------------------------------
# Remote fetchers
# ---------------------------------------------------------------------------


async def fetch_and_cache_sherlock() -> list[dict[str, Any]]:
    """Fetch Sherlock data.json, convert to WMN format, and cache."""
    _ensure_cache_dir()
    try:
        conn = aiohttp.TCPConnector(ssl=_fetch_ssl_ctx())
        async with aiohttp.ClientSession(connector=conn) as session:
            async with session.get(SHERLOCK_DATA_URL, timeout=aiohttp.ClientTimeout(total=30)) as resp:
                if resp.status != 200:
                    return load_cached_remote("sherlock")
                raw = await resp.json(content_type=None)
    except Exception:
        return load_cached_remote("sherlock")

    sites = _convert_sherlock(raw)
    cache_file = _CACHE_DIR / "sherlock.json"
    with open(cache_file, "w", encoding="utf-8") as f:
        json.dump(sites, f)
    return sites


def _convert_sherlock(data: dict[str, Any]) -> list[dict[str, Any]]:
    """Convert Sherlock data.json format to WMN site entries."""
    sites: list[dict[str, Any]] = []
    for name, info in data.items():
        if not isinstance(info, dict):
            continue
        url_template = info.get("url", "")
        if not url_template:
            continue

        # Sherlock uses {} as placeholder; WMN uses {account}
        uri_check = url_template.replace("{}", "{account}")

        error_type = info.get("errorType", "status_code")
        error_msg = info.get("errorMsg", "")
        error_code = info.get("errorCode", 0)

        # Map Sherlock detection to WMN fields
        if error_type == "status_code":
            e_code = 200
            m_code = error_code if error_code else 404
            e_string = ""
            m_string = ""
        elif error_type == "message":
            e_code = 200
            m_code = 200
            e_string = ""
            m_string = str(error_msg) if error_msg else ""
        elif error_type == "response_url":
            e_code = 200
            m_code = 302  # redirect usually
            e_string = ""
            m_string = ""
        else:
            e_code = 200
            m_code = 404
            e_string = ""
            m_string = ""

        entry: dict[str, Any] = {
            "name": name,
            "uri_check": uri_check,
            "e_code": e_code,
            "e_string": e_string,
            "m_string": m_string,
            "m_code": m_code,
            "known": [],
            "cat": _guess_category(name),
            "_source": "sherlock",
        }

        claimed = info.get("username_claimed", "")
        if claimed:
            entry["known"] = [claimed]

        url_main = info.get("urlMain", "")
        if url_main and url_main != uri_check:
            entry["uri_pretty"] = uri_check  # keep original as pretty

        if info.get("isNSFW"):
            entry["cat"] = "xx NSFW xx"

        sites.append(entry)
    return sites


async def fetch_and_cache_maigret() -> list[dict[str, Any]]:
    """Fetch Maigret data.json, convert to WMN format, and cache."""
    _ensure_cache_dir()
    try:
        conn = aiohttp.TCPConnector(ssl=_fetch_ssl_ctx())
        async with aiohttp.ClientSession(connector=conn) as session:
            async with session.get(MAIGRET_DATA_URL, timeout=aiohttp.ClientTimeout(total=60)) as resp:
                if resp.status != 200:
                    return load_cached_remote("maigret")
                raw = await resp.json(content_type=None)
    except Exception:
        return load_cached_remote("maigret")

    sites = _convert_maigret(raw)
    cache_file = _CACHE_DIR / "maigret.json"
    with open(cache_file, "w", encoding="utf-8") as f:
        json.dump(sites, f)
    return sites


# Engine-based URL patterns for Maigret sites that lack explicit URLs
_ENGINE_URL_PATTERNS: dict[str, str] = {
    "XenForo": "{urlMain}/members/{username}.1/",
    "phpBB": "{urlMain}/memberlist.php?mode=viewprofile&un={username}",
    "vBulletin": "{urlMain}/member.php?username={username}",
    "Discourse": "{urlMain}/u/{username}",
    "uCoz": "{urlMain}/{username}/",
    "Flarum": "{urlMain}/u/{username}",
    "Wordpress/Author": "{urlMain}/author/{username}/",
}


def _convert_maigret(data: dict[str, Any]) -> list[dict[str, Any]]:
    """Convert Maigret data.json format to WMN site entries."""
    sites: list[dict[str, Any]] = []

    # Maigret nests sites under "sites" key
    site_list = data.get("sites", data) if isinstance(data, dict) else {}
    if not isinstance(site_list, dict):
        return sites

    for name, info in site_list.items():
        if not isinstance(info, dict):
            continue

        url_template = info.get("url", "")
        url_main = info.get("urlMain", "")

        # If no explicit URL, try to construct from engine + urlMain
        if not url_template and url_main:
            engine = info.get("engine", "")
            pattern = _ENGINE_URL_PATTERNS.get(engine, "")
            if pattern:
                url_template = pattern.replace("{urlMain}", url_main.rstrip("/"))
            else:
                # Skip sites with no URL pattern
                continue

        if not url_template:
            continue

        uri_check = url_template.replace("{username}", "{account}").replace("{}", "{account}")
        if "{account}" not in uri_check:
            continue

        check_type = info.get("checkType", info.get("errorType", "status_code"))
        error_msg = info.get("errorMsg", info.get("absenceStrs", ""))

        if check_type == "status_code":
            e_code = 200
            m_code = 404
            e_string = ""
            m_string = ""
        elif check_type == "message":
            e_code = 200
            m_code = 200
            e_string = ""
            if isinstance(error_msg, list):
                m_string = error_msg[0] if error_msg else ""
            else:
                m_string = str(error_msg) if error_msg else ""
        else:
            e_code = 200
            m_code = 404
            e_string = ""
            m_string = ""

        # Determine category from tags
        tags = info.get("tags", [])
        cat = _maigret_tags_to_cat(tags) if tags else _guess_category(name)

        entry: dict[str, Any] = {
            "name": name,
            "uri_check": uri_check,
            "e_code": e_code,
            "e_string": e_string,
            "m_string": m_string,
            "m_code": m_code,
            "known": [],
            "cat": cat,
            "_source": "maigret",
        }

        claimed = info.get("username_claimed", info.get("usernameClaimed", ""))
        if claimed:
            entry["known"] = [claimed]

        if info.get("isNSFW") or "nsfw" in tags:
            entry["cat"] = "xx NSFW xx"

        sites.append(entry)
    return sites


def _maigret_tags_to_cat(tags: list[str]) -> str:
    """Map Maigret tags to WMN categories."""
    tag_set = {t.lower() for t in tags}
    mapping = {
        "social": "social",
        "dating": "dating",
        "gaming": "gaming",
        "coding": "coding",
        "music": "music",
        "art": "art",
        "photo": "images",
        "video": "video",
        "blog": "blog",
        "finance": "finance",
        "shopping": "shopping",
        "news": "news",
        "tech": "tech",
        "health": "health",
        "hobby": "hobby",
        "business": "business",
        "political": "political",
        "search": "search",
    }
    for tag, cat in mapping.items():
        if tag in tag_set:
            return cat
    return "misc"


# ---------------------------------------------------------------------------
# Category guesser (used when source data lacks category info)
# ---------------------------------------------------------------------------

_CATEGORY_KEYWORDS: dict[str, list[str]] = {
    "social": [
        "facebook", "instagram", "twitter", "x.com", "tiktok", "snapchat",
        "mastodon", "bluesky", "threads", "vk", "linkedin", "weibo",
        "pinterest", "tumblr", "myspace", "gab", "parler", "gettr",
        "truth", "mewe", "minds", "diaspora", "plurk", "ok.ru",
    ],
    "dating": [
        "tinder", "bumble", "hinge", "okcupid", "match", "badoo",
        "pof", "zoosk", "grindr", "dating", "ashley", "seeking",
        "feeld", "coffee", "meetme", "tagged", "friendfinder",
    ],
    "gaming": [
        "steam", "xbox", "playstation", "psn", "epic", "roblox",
        "minecraft", "twitch", "battlenet", "origin", "uplay",
        "riot", "valorant", "fortnite", "league", "dota", "game",
    ],
    "coding": [
        "github", "gitlab", "bitbucket", "stackoverflow", "codepen",
        "dev.to", "npm", "pypi", "rubygems", "crates", "hackr",
        "codeforces", "leetcode", "codewars", "replit", "gitea",
    ],
    "finance": [
        "paypal", "venmo", "cashapp", "binance", "coinbase", "crypto",
        "bitcoin", "etoro", "robinhood", "trading", "forex", "stock",
    ],
    "video": [
        "youtube", "vimeo", "dailymotion", "rumble", "bitchute",
        "odysee", "peertube", "twitch",
    ],
    "music": [
        "spotify", "soundcloud", "bandcamp", "lastfm", "deezer",
        "tidal", "mixcloud", "audiomack",
    ],
    "images": [
        "flickr", "imgur", "deviantart", "500px", "unsplash",
        "pexels", "pixabay", "shutterstock", "eyeem",
    ],
    "shopping": [
        "ebay", "etsy", "amazon", "poshmark", "depop", "mercari",
        "shopify", "redbubble", "wish", "aliexpress",
    ],
    "tech": [
        "docker", "npm", "pypi", "crates", "nuget", "hackernews",
        "producthunt", "techcrunch",
    ],
    "blog": [
        "medium", "substack", "wordpress", "blogger", "ghost",
        "hashnode", "dev.to",
    ],
    "xx NSFW xx": [
        "onlyfans", "fansly", "pornhub", "xvideos", "chaturbate",
        "xhamster", "nsfw", "adult", "xxx",
    ],
}


def _guess_category(name: str) -> str:
    name_lower = name.lower()
    for cat, keywords in _CATEGORY_KEYWORDS.items():
        for kw in keywords:
            if kw in name_lower:
                return cat
    return "misc"


# ---------------------------------------------------------------------------
# Merge & dedup
# ---------------------------------------------------------------------------


def _domain_key(uri: str) -> str:
    """Extract domain from a URI for dedup purposes."""
    try:
        parsed = urlparse(uri)
        return parsed.netloc.lower().removeprefix("www.")
    except Exception:
        return uri.lower()


def merge_and_dedup(
    *site_lists: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """Merge multiple site lists and deduplicate by domain + path pattern.

    Priority: wmn > extended > sherlock > maigret
    """
    source_priority = {"wmn": 0, "extended": 1, "sherlock": 2, "maigret": 3}
    seen: dict[str, dict[str, Any]] = {}

    for sites in site_lists:
        for site in sites:
            uri = site.get("uri_check", "")
            if not uri:
                continue
            key = _domain_key(uri) + urlparse(uri).path.split("{")[0]
            source = site.get("_source", "unknown")
            priority = source_priority.get(source, 99)

            if key not in seen or priority < source_priority.get(
                seen[key].get("_source", "unknown"), 99
            ):
                seen[key] = site

    result = sorted(seen.values(), key=lambda s: s.get("name", "").lower())
    return result


def get_all_categories(sites: list[dict[str, Any]]) -> list[str]:
    """Return sorted list of all categories present in the sites."""
    cats = {s.get("cat", "misc") for s in sites}
    return sorted(cats)


# ---------------------------------------------------------------------------
# High-level loaders
# ---------------------------------------------------------------------------


def load_all_local() -> list[dict[str, Any]]:
    """Load WMN + extended + cached remote data (no network)."""
    wmn = load_wmn_data()
    extended = load_extended_data()
    sherlock_cached = load_cached_remote("sherlock")
    maigret_cached = load_cached_remote("maigret")
    return merge_and_dedup(wmn, extended, sherlock_cached, maigret_cached)


async def load_all_with_update() -> tuple[list[dict[str, Any]], dict[str, int]]:
    """Load all data including fresh remote fetch. Returns (sites, stats)."""
    wmn = load_wmn_data()
    extended = load_extended_data()
    sherlock = await fetch_and_cache_sherlock()
    maigret = await fetch_and_cache_maigret()

    merged = merge_and_dedup(wmn, extended, sherlock, maigret)

    stats = {
        "wmn": len(wmn),
        "extended": len(extended),
        "sherlock": len(sherlock),
        "maigret": len(maigret),
        "total_merged": len(merged),
    }
    return merged, stats
