name: Validate JSON
on: [pull_request]
jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate JSON
        uses: OrRosenblatt/validate-json-action@9635f1e0bda5d3e5b41598de4c9442bc0e2d9353
        with:
          schema: wmn-data-schema.json
          json: wmn-data.json
