name: Validate JSON
on: [pull_request]
jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate JSON
        uses: OrRosenblatt/validate-json-action@0.1.0
        with:
          schema: wmn-data-schema.json
          jsons: wmn-data.json
